# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: harvardml
email: srush@seas.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Home of the Harvard SEAS machine learning group.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ml.seas.harvard.edu/" # the base hostname & protocol for your site
twitter_username: 
github_username:  harvardml

# Build settings
markdown: kramdown
